# Generated by Django 2.1.1 on 2018-10-04 12:02

from django.db import migrations, models
import kitchen.models
import kitchen.storage


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0006_auto_20180930_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='everyone',
            name='cover',
            field=models.FileField(null=True, storage=kitchen.storage.OverwriteStorage(), upload_to=kitchen.models.Everyone.user_directory_path_cover),
        ),
        migrations.AlterField(
            model_name='everyone',
            name='dp',
            field=models.FileField(null=True, storage=kitchen.storage.OverwriteStorage(), upload_to=kitchen.models.Everyone.user_directory_path_dp),
        ),
    ]
