# Generated by Django 2.1.1 on 2018-09-30 12:03

from django.db import migrations, models
import kitchen.models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0003_everyone'),
    ]

    operations = [
        migrations.AddField(
            model_name='everyone',
            name='first_name',
            field=models.CharField(default='F', max_length=100),
        ),
        migrations.AddField(
            model_name='everyone',
            name='last_name',
            field=models.CharField(default='L', max_length=100),
        ),
        migrations.AlterField(
            model_name='everyone',
            name='cover',
            field=models.FileField(upload_to=kitchen.models.Everyone.user_directory_path_cover),
        ),
        migrations.AlterField(
            model_name='everyone',
            name='dp',
            field=models.FileField(upload_to=kitchen.models.Everyone.user_directory_path_dp),
        ),
    ]
