# Generated by Django 2.1.1 on 2018-09-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0005_auto_20180930_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='everyone',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='everyone',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='everyone',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
