# Generated by Django 2.1.1 on 2018-10-20 04:23

from django.db import migrations, models
import django.db.models.deletion
import kitchen.models
import kitchen.storage


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0007_auto_20181004_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=200)),
                ('dir', models.CharField(max_length=10000)),
                ('cal', models.IntegerField(default=0)),
                ('time_hr', models.IntegerField(default=0)),
                ('time_min', models.IntegerField(default=0)),
                ('rec_img', models.FileField(null=True, storage=kitchen.storage.OverwriteStorage(), upload_to=kitchen.models.Recipe.user_directory_path_rec)),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='rec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.Recipe'),
        ),
    ]
