# Generated by Django 2.1.1 on 2018-10-20 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0008_auto_20181020_0423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='chef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kitchen.Everyone'),
        ),
        migrations.AddField(
            model_name='rating',
            name='rec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.Recipe'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.Everyone'),
        ),
    ]
