# Generated by Django 2.1.1 on 2018-10-20 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0009_auto_20181020_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kitchen.Recipe'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kitchen.Everyone'),
        ),
    ]
